package com.pcnc2000.flutter_open_tok_video_chat

import android.os.Handler
import android.os.Looper
import androidx.annotation.NonNull
import com.pcnc2000.flutter_open_tok_video_chat.archiving.Archiving
import com.pcnc2000.flutter_open_tok_video_chat.archiving.ArchivingFactory
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import com.pcnc2000.flutter_open_tok_video_chat.config.SdkState
import com.pcnc2000.flutter_open_tok_video_chat.multi_video.MultiVideo
import com.pcnc2000.flutter_open_tok_video_chat.multi_video.MultiVideoFactory
import com.pcnc2000.flutter_open_tok_video_chat.one_to_one_video.OneToOneVideo
import com.pcnc2000.flutter_open_tok_video_chat.one_to_one_video.OpentokVideoFactory
import com.pcnc2000.flutter_open_tok_video_chat.screen_sharing.ScreenSharing
import com.pcnc2000.flutter_open_tok_video_chat.screen_sharing.ScreenSharingFactory
import com.pcnc2000.flutter_open_tok_video_chat.singaling.Signalling
import io.flutter.plugin.common.BinaryMessenger

package com.pcnc2000.flutter_open_tok_video_chat

import android.os.Handler
import android.os.Looper
import androidx.annotation.NonNull
import com.pcnc2000.flutter_open_tok_video_chat.archiving.Archiving
import com.pcnc2000.flutter_open_tok_video_chat.archiving.ArchivingFactory
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import com.pcnc2000.flutter_open_tok_video_chat.config.SdkState
import com.pcnc2000.flutter_open_tok_video_chat.multi_video.MultiVideo
import com.pcnc2000.flutter_open_tok_video_chat.multi_video.MultiVideoFactory
import com.pcnc2000.flutter_open_tok_video_chat.one_to_one_video.OneToOneVideo
import com.pcnc2000.flutter_open_tok_video_chat.one_to_one_video.OpentokVideoFactory
import com.pcnc2000.flutter_open_tok_video_chat.screen_sharing.ScreenSharing
import com.pcnc2000.flutter_open_tok_video_chat.screen_sharing.ScreenSharingFactory
import com.pcnc2000.flutter_open_tok_video_chat.singaling.Signalling
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.embedding.engine.plugins.FlutterPlugin


class MainActivity : FlutterActivity() {

}


