name: flutter_open_tok_video_chat
description: Flutter app showcase a range of OpenTok SDK features


publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:


  uses-material-design: true

  plugin:
    platforms:
      android:
        package: com.pcnc2000.flutter_open_tok_video_chat
        pluginClass: MainActivity
      ios:
        pluginClass: GeneratedPluginRegistrant